name: Code Checks

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Cache
      uses: actions/cache@v2
      id: cache-venv
      with:
        path: ./.venv/
        key: ${{ matrix.python-version }}-venv-${{ hashFiles('setup.py', '.github/workflows/unittest.yml') }}
        restore-keys: |
          ${{ matrix.python-version }}-venv-
    - name: Cache Status
      run: echo "${{steps.cache-venv.outputs.cache-hit}}"
    - name: Install
      run: python -m venv venv && source venv/bin/activate && make install
      if: steps.cache-venv.outputs.cache-hit != 'true'
    - name: Unittest
      run: python -m venv venv && source venv/bin/activate && make test
